# create a numpy array of 5 zeros.
check datatype, itemsize and shape of above

In [2]:
import numpy as np

In [19]:
a = np.zeros(5, dtype = int)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0 0 0 0 0]
int32
4
(5,)


# create a numpy array of ones of shape (5,4)

In [24]:
a = np.ones(shape= (5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# create a matrix of shape 4,5 with numbers from 1-20

In [28]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# multiply all elements of above array by 10

In [30]:
print(a*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


# print odd elements from array

In [13]:
a = np.arange(1,21).reshape(4,5)
print(a)

a[a%2 == 1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# replace all even elements by their negative

In [40]:
a = np.arange(1,21).reshape(4,5)
r = a*(-1)
print(r)

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]
 [-16 -17 -18 -19 -20]]


# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [42]:
M1 = np.arange(1,17).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# create a transpose of above matrix call it M2

In [45]:
M2 = M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


# find sum of above matrix M3 = (M1 + M2)

In [47]:
M3 = M1+M2 
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


# Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [50]:
MT1 = M3.T
print(MT1)
print(M3==MT1)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


# find diffrence of M4 = (M1 - M2)

In [52]:
M4 = M1 - M2 
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [55]:
MT2 = M4.T
print(MT2)
print(M4== -MT2)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


# Create a matrix (3x4) R1 of random numbers between 10-40

In [3]:
import random 
R1 = np.random.randint(10,40,12).reshape(3,4)
#R1= R1.reshape(3,4)
print(R1)

[[27 17 15 24]
 [26 31 27 12]
 [34 12 31 17]]


# find min and max column wise

In [9]:
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)
print()
print(R1.max(axis = 0))
print()

print(R1.min(axis = 0))

[[13 16 38 22]
 [25 37 26 19]
 [23 22 15 39]]

[25 37 38 39]

[13 16 15 19]


# replace the last column with sum of all the columns

In [71]:
import random 
R1 = np.random.randint(10,40,12).reshape(3,4)
R2 = R1.sum(axis= 1)
print(R1)
print()
print(R2)

R1[:,-1] = R2
print(R1)

[[33 15 32 29]
 [15 26 37 31]
 [11 34 37 18]]

[109 109 100]
[[ 33  15  32 109]
 [ 15  26  37 109]
 [ 11  34  37 100]]


# create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1

In [91]:
R1 = np.random.randint(10,40,12)
print(R1)
print()
R2 = R1.astype(np.float)
count = 0
for i in range(0,len(R2)):
    if R2[i]%2 == 0:
        R2[i] = np.nan
        count = count + 1

print(R2)
print(count)



[21 27 23 39 19 33 15 22 20 21 28 26]

[21. 27. 23. 39. 19. 33. 15. nan nan 21. nan nan]
4


In [90]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
