### 1. Convert a Tuple t = (1,2,3,4,5) to a list

In [1]:
t = (1,2,3,4,5)
list(t)

[1, 2, 3, 4, 5]

### 2. WAP to join a list and a tuple:
###### L = [1,3,5,7]
###### T = (8,6,4,2)
###### Store the result in a list LS

In [2]:
L = [1,3,5,7]
T = (8,6,4,2)
L.extend(T)
L

[1, 3, 5, 7, 8, 6, 4, 2]

In [5]:
L = [1,3,5,7]
T = (8,6,4,2)
LS = L + list(T)
LS

[1, 3, 5, 7, 8, 6, 4, 2]

#### 3. What is difference between list and tuple.

In [6]:
#.1. List is mutable whereas Tuple is immutable
#.2. List is a bit slower than Tuple
#.3. List takes a bit more memory than tuple

#### 4. Print the list in reverse order
l = [‘a’, ‘d’, ‘c’, ‘A’, ‘C’]

In [9]:
l = ['a', 'd', 'c', 'A','C']
l.reverse()
l

['C', 'A', 'c', 'd', 'a']

##### 5. Print Elements at Odd indexes from a list (Do not use loop)
l = [10,11,20, 21,30, 31, 40, 41]

In [10]:
l = [10,11,20, 21,30, 31, 40, 41]
l[::2]

[10, 20, 30, 40]

#### 6. How many ways you can copy a list.

In [11]:
#1.
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = l1[:] 
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [12]:
#2.
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = l1
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [13]:
#3
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = l1.copy()
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [14]:
#4
import copy 
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = copy.copy(l1)
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [15]:
#5
import copy
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = copy.deepcopy(l1)
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [16]:
#6
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = [] 
l2.extend(l1) 
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [17]:
#7
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = list(l1) 
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [18]:
#8
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 = [n for n in l1]  
print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


In [20]:
#9
l1 = [10,11,20, 21,30, 31, 40, 41]
l2 =[] 
for item in l1: l2.append(item) 

print(l1)
print(l2)

[10, 11, 20, 21, 30, 31, 40, 41]
[10, 11, 20, 21, 30, 31, 40, 41]


### 7. Predict output
##### n_list = ["Happy", [2,0,1,5]]
##### print(n_list[0][1])
##### print(n_list[1][3])

In [22]:
#Sol
"""
a
5
"""

'\na\n5\n'

#### 8. Predict output
###### odd = [2,4,6,8]
###### odd[0] = 1
###### print(odd)
###### odd[1:4] = [3,5,7]
###### print(odd)

In [24]:
#Sol:
"""
[1, 4, 6, 8]
[1, 3, 5, 7]
"""

'\n[1, 4, 6, 8]\n[1, 3, 5, 7]\n'

##### 9. Predict output
###### odd = [1,3,5]
###### odd.append([7,9])
###### print(odd)
###### odd.extend([11,13])
###### print(odd)

In [26]:
#Sol:
"""
[1, 3, 5, [7, 9]]
[1, 3, 5, [7, 9], 11, 13]
"""

'\n[1, 3, 5, [7, 9]]\n[1, 3, 5, [7, 9], 11, 13]\n'

#### 10. notePredict output
##### x = 1,2,3; print(type(x))
##### x = (1) ; print(type(x))
##### x = 1; print(type(x))
##### x = 1, ; print(type(x))

In [28]:
#Sol:
"""
<class 'tuple'>
<class 'int'>
<class 'int'>
<class 'tuple'>
"""

"\n<class 'tuple'>\n<class 'int'>\n<class 'int'>\n<class 'tuple'>\n"

### 11. Try to represent a matrix with following data in python:
##### 1 2 3
##### 4 5 6
##### 7 8 9

In [30]:
from numpy import matrix
A = [[1,2,3],[4,5,6],[7,8,9]]
B = matrix(A)
print(A)
print(B)
print(type(A))
print(type(B))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
<class 'numpy.matrix'>


### 12. Predict output
##### t = tuple('string')
##### print(t)
##### print(t[::-1])
##### print(t[::2][::-2])

In [32]:
#Sol:
"""
('s', 't', 'r', 'i', 'n', 'g')
('g', 'n', 'i', 'r', 't', 's')
('n', 's')
"""

"\n('s', 't', 'r', 'i', 'n', 'g')\n('g', 'n', 'i', 'r', 't', 's')\n('n', 's')\n"

### 13. Predict output
##### t = tuple([10,20,30,40,50,60])
##### print(60 in t)
##### print('60' in t)
##### print(t.count(10))
##### print(t.index(40))

In [34]:
#Sol:
"""
True
False
1
3
"""

True
False
1
3


### 14. Write a program to input a string and print if it is palindrome or not.

In [49]:
str1 = input("Enter a string:")

if str1 == str1[::-1]:
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter a string:abcdcba
Palindrome


### 15. Use the range method and create a tuple containing the following values:
##### (20, 15, 10, 5)

In [55]:
tuple(range(20,1,-5))

(20, 15, 10, 5)

### 16. WAP to convert string to list of characters.

In [56]:
str1 = "string"
list(str1)

['s', 't', 'r', 'i', 'n', 'g']

### 17. What is the return type of:
##### print(type( '1 2'.split() ))
##### print(type( [1, 3, 2].sort() ))
##### print(type( 'abc'.upper() ))
##### print(type( 1 in [1, 2] ))

In [1]:
#Sol:
"""
<class 'list'>
<class 'NoneType'>
<class 'str'>
<class 'bool'>
"""

<class 'list'>
<class 'NoneType'>
<class 'str'>
<class 'bool'>
