In [ ]:
x = 1

In [ ]:
#      1 ,   10,     3,     4
    1000   1004   1008   1012
    
# [1,2,3,4]
# 

In [1]:
import platform

In [6]:
print(dir(platform))
print(platform.python_implementation())
print(platform.machine())

['_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_component_re', '_default_architecture', '_follow_symlinks', '_ironpython26_sys_version_parser', '_ironpython_sys_version_parser', '_java_getprop', '_libc_search', '_mac_ver_xml', '_node', '_norm_version', '_platform', '_platform_cache', '_pypy_sys_version_parser', '_sys_version', '_sys_version_cache', '_sys_version_parser', '_syscmd_file', '_syscmd_uname', '_syscmd_ver', '_uname_cache', '_ver_output', '_ver_stages', 'architecture', 'collections', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'python_compiler', 'python_implementation', 'python_revision', 'python_version', 'python_version_tuple', 're', 'release', 'sys', 'system', 'system_alias', 'uname', 'uname_result', 'version', 'win32_edition', 'win32_

In [9]:
import numpy as np

In [8]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [10]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [11]:
print(np.array)

<built-in function array>


In [13]:
r = np.array([1,2,3])
print(r)
print(type(r))
print(dir(r))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr_

In [32]:
r = np.array([1,2,3])
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)
print(r.ndim)

int64
8
3
(3,)
1


In [22]:
r = np.array( [
    [1,2,3], 
    [1,2,3]
])
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)

int64
8
6
(2, 3)


In [23]:
r = np.array( [
    [1,2,3], 
    [1,2,3, 4]
])
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)
print(r)

object
8
2
(2,)
[list([1, 2, 3]) list([1, 2, 3, 4])]


In [27]:
r = np.array( [
    [11,2,3], 
    [1,2,3]
], dtype="int8")
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)
print(r)

int8
1
6
(2, 3)
[[11  2  3]
 [ 1  2  3]]


In [33]:
r = np.array( [
    [11,2,3], 
    [1,2,3]
], dtype=np.int8)
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)
print(r)
print(r.ndim)
print(r.T)

int8
1
6
(2, 3)
[[11  2  3]
 [ 1  2  3]]
2
[[11  1]
 [ 2  2]
 [ 3  3]]


In [ ]:
a [1,2,3,4,5,6]


[[1,2,3]
 [4,5,6]]

[[1,2]
 [3,4]
 [5,6]]

In [37]:
r = np.array( [1,2,3,4,5,6], dtype=np.int8, ndmin=3)
print(r.dtype)
print(r.itemsize)
print(r.size)
print(r.shape)
print(r)
print(r.ndim)
print(r.T)

int8
1
6
(1, 1, 6)
[[[1 2 3 4 5 6]]]
3
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]


In [41]:
n = np.int8()
print(n, type(n))
n = int()
print(n, type(n))

0 <class 'numpy.int8'>
0 <class 'int'>


In [51]:
r = np.array(["abc", "pqr", "3"], dtype='<S10')
print(r)
print(r.dtype)

[b'abc' b'pqr' b'3']
|S10


In [55]:
r = np.array([1, "pqr", list()])
print(r)
print(r.dtype)

[1 'pqr' list([])]
object


In [ ]:
Row major  1,2,3,  4,5,6 (2,3)
Col major  1,2,3,  4,5,6 (2,3)
Addres calculation

In [58]:
np.random.randn(10)

array([ 0.14728554, -1.27052093, -0.51559513, -0.40557591, -1.29211325,
        0.33373253,  0.73450467,  1.42567   , -0.44616479, -0.35473187])

In [61]:
np.random.randint(10,20, 10)

array([19, 16, 14, 18, 17, 15, 17, 15, 11, 11])

In [62]:
np.random.randint(10,20, (2,3))

array([[10, 16, 18],
       [12, 13, 15]])

In [66]:
a = np.arange(10, dtype=np.float32)
print(a)
a = np.arange(10,20)
print(a)
a = np.arange(10,20, 2)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [81]:
a = np.linspace(10,20,6)
print(a)
a = np.linspace(10,20,100)
print(a)

[10. 12. 14. 16. 18. 20.]
[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 

In [ ]:
# [10 20) n = 5

d = (20-10)/(n -1) = (10)/5

10 , 10 + 1d, 10+ 2d... 10 + 5d
10 , 12,     , 14,      16, 18, 20

In [79]:
np.zeros(shape=(3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Reshape and Resize

In [90]:
a = np.arange(12)
print(a)
print()

r = a.reshape(2,6)
print(r)
print()
print(a)


r = a.reshape(3,4)
print(r)
print()

r = a.reshape(3,2,2)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [89]:
a = np.arange(12)
print(a)
print()

r = a.resize(2,7)
print(r)
print()
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]

None

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11  0  0]]


In [93]:
# indexing and slicing

In [97]:
a = np.arange(10,22)
print(a, len(a))

[10 11 12 13 14 15 16 17 18 19 20 21] 12


In [103]:
print(a[0])
print(a[-1])
print(a[0:3])
print(a[0:-1])
print(a[0:-1:2])
print(a[::-2])

10
21
[10 11 12]
[10 11 12 13 14 15 16 17 18 19 20]
[10 12 14 16 18 20]
[21 19 17 15 13 11]


In [104]:
a[0] = a[0]*10
print(a)

[100  11  12  13  14  15  16  17  18  19  20  21]


In [98]:
m = np.arange(10,22).reshape(3,4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [107]:
print(m[0])
print(m[0][0])
print(m[0, 0])

[10 11 12 13]
10
10


In [112]:
print(m)
print()

print(m[0:2])
print(m[:,0:2])
print(m[:][0:2])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[10 11 12 13]
 [14 15 16 17]]
[[10 11]
 [14 15]
 [18 19]]
[[10 11 12 13]
 [14 15 16 17]]


In [115]:
print(m)
print()
print(m[2,1:3])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[19 20]


In [122]:
m = np.arange(10,22).reshape(3,4)
print(m)

m[2,1:3] = 0
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12 13]
 [14 15 16 17]
 [18  0  0 21]]


In [121]:
m = np.arange(10,22).reshape(3,4)
print(m)

m[2,1:3] = m[2,1:3] + 3
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[10 11 12 13]
 [14 15 16 17]
 [18 22 23 21]]


In [ ]:
# broadcasting and arithmetic

In [123]:
m = np.arange(10,22).reshape(3,4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [124]:
m * 100

array([[1000, 1100, 1200, 1300],
       [1400, 1500, 1600, 1700],
       [1800, 1900, 2000, 2100]])

In [127]:
m1 = np.arange(10,22).reshape(3,4)
print(m1)
print()

m2 = np.arange(110,122).reshape(3,4)
print(m2)
print()

print(m1 + m2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[110 111 112 113]
 [114 115 116 117]
 [118 119 120 121]]

[[120 122 124 126]
 [128 130 132 134]
 [136 138 140 142]]


In [128]:
m1 = np.arange(10,22).reshape(3,4)
print(m1)
print()

m2 = np.arange(110,122).reshape(4,3)
print(m2)
print()

print(m1 + m2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[110 111 112]
 [113 114 115]
 [116 117 118]
 [119 120 121]]



ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [135]:
m1 = np.arange(10,22).reshape(3,4)
print(m1)
print()

m2 = np.arange(4)
print(m2)
print()

print(m1 / m2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[0 1 2 3]

[[        inf 11.          6.          4.33333333]
 [        inf 15.          8.          5.66666667]
 [        inf 19.         10.          7.        ]]


<ipython-input-135-376f2db4fc2d>:9: RuntimeWarning: divide by zero encountered in true_divide
  print(m1 / m2)


In [132]:
m1 = np.arange(10,22).reshape(3,4)
print(m1)
print()

m2 = np.arange(3)
print(m2)
print()

print(m1 + m2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[0 1 2]



ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [155]:
# logical operations
a = np.arange(10,22)
print(a)

print(a%2 == 0)

[10 11 12 13 14 15 16 17 18 19 20 21]
[ True False  True False  True False  True False  True False  True False]


In [157]:
# logical operations
a = np.random.randint(10,22,5)
print(a)

print(a < 15)

[15 10 12 10 14]
[False  True  True  True  True]


In [137]:
# numpy special  values
print(numpy.nan, type(numpy.nan))
print(numpy.inf, type(numpy.inf))

nan <class 'float'>
inf <class 'float'>


In [143]:
print(np.int8(10) > np.int8(5))
print(np.int8(10) > np.int8(15))

print()
print(np.float64(10.5) > np.int8(15))
print(np.nan > np.int8(15))
print(np.nan < np.int8(15))

print()
print(np.nan < np.nan)
print(np.nan > np.nan)
print(np.nan == np.nan)
print(np.nan != np.nan)

True
False

False
False
False

False
False
False
True


In [145]:
print(np.nan + np.int8(10))
print(np.nan * np.int8(10))

nan
nan


In [ ]:
# aggregation

In [148]:

a = np.arange(10,22, dtype=np.float64)
print(a)

print(a.sum())
print(a.mean())

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
186.0
15.5


In [151]:
m = np.arange(10,22, dtype=np.float64).reshape(3,4)
print(m)

print(m.sum())
print(m.mean())

print()
print(m.sum(axis=1))
print(m.mean(axis=1))

print()
print(m.sum(axis=0))
print(m.mean(axis=0))

[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]
186.0
15.5

[46. 62. 78.]
[11.5 15.5 19.5]

[42. 45. 48. 51.]
[14. 15. 16. 17.]


In [153]:
# aggregates with nan give nan in numpy
a = np.arange(10,22, dtype=np.float64)
a[0:4:2] = np.nan
print(a)

print(a.sum())

[nan 11. nan 13. 14. 15. 16. 17. 18. 19. 20. 21.]
nan


In [165]:
#  boolean indexing
a = np.random.randint(10,22,5)
print(a)
r = a < 15
print(r)
print(a[r])


[21 20 12 11 10]
[False False  True  True  True]
[12 11 10]


In [162]:
# replace all even values with square nd odd values with their half
a = np.arange(10,22).reshape(3,4)
print(a)

e_idx  = a%2 == 0
o_idx = ~e_idx

print(e_idx)
print(o_idx)

a[e_idx] = a[e_idx] ** 2
a[o_idx] = a[o_idx] / 2

print()
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]

[[100   5 144   6]
 [196   7 256   8]
 [324   9 400  10]]


In [216]:
# sequence/list/tuple based indexing
a = np.arange(10,22)

print(a)
print(a[ [1,4,5] ])

idx = ((7,4,5),)
print(a[idx])

[10 11 12 13 14 15 16 17 18 19 20 21]
[11 14 15]
[17 14 15]


In [181]:
m = np.arange(10,22).reshape(3,4)
print(m)

idx = ((1,1,2),(2,1,3))
print()
print(m[(1,1,2),(2,1,3)])


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[16 15 21]


In [189]:
# nan
# aggregates with nan give nan in numpy
a = np.arange(10,22, dtype=np.float64)
a[0:4:2] = np.nan
print(a)

print(np.isnan(a))
print(a == np.nan) # this doesn't work

[nan 11. nan 13. 14. 15. 16. 17. 18. 19. 20. 21.]
[ True False  True False False False False False False False False False]
[False False False False False False False False False False False False]


In [ ]:
# combining boolean and arithmetic operations

In [203]:
a = np.random.randint(10,22,5)
print(a)
r = a < 15
print(r)
print(r.sum())


[10 12 12 15 20]
[ True  True  True False False]
3


In [204]:
#  & => and    ;   | => or  ;  ~ => not
# and, or operators cannot be used with numpy arrays
a = np.random.randint(10,22,10)
print(a)
r = (a >= 12) and (a <= 15) 
print(r)
print(r.sum())


[20 13 16 14 14 11 15 20 13 20]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [202]:
a = np.random.randint(10,22,10)
print(a)
r = (a >= 12) & (a <= 15) #  & => and    ;   | => or
print(r)
print(r.sum())


[11 15 21 13 14 13 13 16 21 10]
[False  True False  True  True  True  True False False False]
5


In [207]:
# and, all

a = np.random.randint(10,22,10)
print(a)
r = a <= 15
print(r)

print(r.any())
print(r.all())

print()
print(a.any())
print(a.all())


[19 18 11 15 19 19 14 19 11 16]
[False False  True  True False False  True False  True False]
True
False

True
True


In [211]:
# check if array contains a nan
a = np.arange(10,22, dtype=np.float64)
a[0:4:2] = np.nan
print(a)

print(np.isnan(a).any())
print(np.isnan(a).sum())

print()
a = np.arange(10,22, dtype=np.float64)
print(a)

print(np.isnan(a).any())
print(np.isnan(a).sum())

[nan 11. nan 13. 14. 15. 16. 17. 18. 19. 20. 21.]
True
2

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
False
0


In [219]:
# where
a = np.arange(10,22).reshape(3,4)
print(a)

pos = a%2 == 0
print(pos)
print(np.where(pos))


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))


In [224]:
# where
a = np.arange(10,22).reshape(3,4)
print(a)
print(pos)


# where (bools, scalar, scalar)
print()
pos = a%2 == 0
print(np.where(pos, 11, 222))

# where (bools, mat, scalar)
print()
pos = a%2 == 0
print(np.where(pos, a, 0))


# where (bools, scalar, mat)
print()
pos = a%2 == 0
print(np.where(pos, 0, a))


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]

[[ 11 222  11 222]
 [ 11 222  11 222]
 [ 11 222  11 222]]

[[10  0 12  0]
 [14  0 16  0]
 [18  0 20  0]]

[[ 0 11  0 13]
 [ 0 15  0 17]
 [ 0 19  0 21]]


In [226]:
# replace all even values with square nd odd values with their half
a = np.arange(10,22).reshape(3,4)
print(a)

e_idx  = a%2 == 0

print(e_idx)

print(np.where(e_idx, a**2, a//2))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[[100   5 144   6]
 [196   7 256   8]
 [324   9 400  10]]
