### 1. create a numpy array of 5 zeros. check datatype, itemsize and shape of above

In [4]:
import numpy as np
r = np.array([0, 0, 0, 0, 0])
print(r.dtype)
print(r.itemsize)
print(r.shape)

int32
4
(5,)


### 2. create a numpy array of ones of shape (5,4)

In [7]:
print(np.ones(shape=(5,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 3. create a matrix of shape 4,5 with numbers from 1-20

In [13]:
m=np.arange(1,21).reshape(4,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### 4. multiply all elements of above array by 10

In [15]:
print(m*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


### 5. print odd elements from array

In [18]:
print(m)
print()
odd=m%2!=0
print(m[odd])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 1  3  5  7  9 11 13 15 17 19]


### 6. replace all even elements by their negative

In [19]:
print(m)
print()
even=m%2==0
print(-m[even])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


### 7. create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [23]:
m1= np.arange(1,17).reshape(4,4)
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 8. create a transpose of above matrix call it M2

In [30]:
m2=m1.transpose()
print(m2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### 9. find sum of above matrix M3 = (M1 + M2)

In [33]:
print(m1.shape)
print(m2.shape)
m3=m1+m2
print(m3)

(4, 4)
(4, 4)
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


### 10. Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [35]:
mt1=m3.transpose()
print(m3==mt1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 11. find diffrence of M4 = (M1 - M2)

In [36]:
m4=m1-m2
print(m4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


### 12. Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [38]:
mt2=m4.transpose()
print(m4)
print(mt2)
print(m4==mt2)
print(m4==-mt2)


[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 13. create a matrix (3x4) R1 of random numbers between 10-40

In [42]:
import random
R1=np.random.randint(10,40,(3,4))
print(R1)

[[31 20 23 15]
 [27 24 31 15]
 [10 11 29 28]]


### 14. find min and max column wise

In [46]:
print(R1.min(axis=0))# min of row
print(R1.min(axis=1))# min of column
print(R1.max(axis=0))# max of row
print(R1.max(axis=1))# max of column

[10 11 23 15]
[15 15 10]
[31 24 31 28]
[31 31 29]


### 15. replace the last column with sum of all the columns

In [66]:
print(R1)
print(R1.sum(axis=1))
R1[(0,1,2),(3,3,3)] = R1.sum(axis=1)
print(R1)

[[ 31  20  23 163]
 [ 27  24  31 179]
 [ 10  11  29 128]]
[237 261 178]
[[ 31  20  23 237]
 [ 27  24  31 261]
 [ 10  11  29 178]]


### 16. create a matrix (3x4) R1 of random numbers between 10-40

In [3]:
import numpy as np
import random
R1=np.random.randint(10,40,(3,4))
#R1.dtype=np.float64
print(R1)

[[27 18 16 29]
 [36 10 33 29]
 [23 25 15 38]]


### 17. replace all even elements with nan in R1

In [8]:

e_idx=R1%2==0

print(e_idx)
a=np.where(e_idx,np.nan,R1**1)
print(a)

[[False  True  True False]
 [ True  True False False]
 [False False False  True]]
[[27. nan nan 29.]
 [nan nan 33. 29.]
 [23. 25. 15. nan]]


### 18. count number of nan in R1

In [10]:
print(np.isnan(a).sum())

5


### 19. check output of this code

In [11]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
