## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)



In [10]:
# 1  create a numpy array of 5 zeros.check datatype, itemsize and shape of above

import numpy as np
zer = np.zeros((1,5))
print(zer.dtype)
print(zer.itemsize)
print(zer.shape)

float64
8
(1, 5)


In [14]:
# 2 create a numpy array of ones of shape (5,4)

one = np.ones((5,4),dtype=np.int64)
print(one)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
# 3 create a matrix of shape 4,5 with numbers from 1-20
m= np.arange(20).reshape(4,5)
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
# 4 multiply all elements of above array by 10

print(m*10)

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [35]:
# 5 print odd elements from array
n = np.arange(15).reshape(3,5)
print(n)
print()
odd_idx = n%2!=0
print(n[odd_idx])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[ 1  3  5  7  9 11 13]


In [29]:
# 6  replace all even elements by their negative

# using the above array
even_idx = n%2==0
pos = np.where(even_idx,-n,n)
print("Original :")
print(n)
print("Negated : ")
print(pos)

Original :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Negated : 
[[  0   1  -2   3  -4]
 [  5  -6   7  -8   9]
 [-10  11 -12  13 -14]]


In [36]:
# 7 create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = (np.arange(16).reshape(4,4))
print(M1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
# 8 create a transpose of above matrix call it M2

M2=np.transpose(M1)
print(M2)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [42]:
# 9 find sum of above matrix M3 = (M1 + M2)
M3=M1+M2
print(M3)


[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


In [84]:
# 10 Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = np.transpose(M3)
print(M3==MT1)
check=(M3==MT1)
print(check.all())

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
True


In [46]:
#11 Find diffrence of M4 = (M1 - M2)
M4=(M1-M2)
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [88]:
# 12 Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT2=np.transpose(M4)
print("M4")
print()
print(M4)
print("MT2")
print()
print(MT2)
print()
print(M4==MT2)
print()
checkA=(M4==MT2)
print(checkA.all())
print()
print(M4==-MT2)
checkB=(M4==-MT2)
print(checkB.all())

M4

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
MT2

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

False

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
True


In [58]:
# 13 create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size=(3,4))
print(R1)

[[11 38 19 24]
 [14 30 24 27]
 [22 16 33 31]]


In [67]:
# 14 find min and max column wise
# Using the above matrix
print(np.amin(R1,axis=0))
print(np.amax(R1,axis=0))

[11 16 19 24]
[22 38 33 31]


In [73]:
# 15 replace the last column with sum of all the columns
print(R1)
print(R1.sum(axis=1))
R1[(0,1,2),(3,3,3)]=R1.sum(axis=1)
print(R1)

[[ 11  38  19  92]
 [ 14  30  24  95]
 [ 22  16  33 102]]
[160 163 173]
[[ 11  38  19 160]
 [ 14  30  24 163]
 [ 22  16  33 173]]


In [77]:
# 16 create a matrix (3x4) R1 of random numbers between 10-40

R1= np.random.randint(10,40,size=(3,4))
print(R1)

[[25 35 12 22]
 [38 26 22 34]
 [17 22 19 23]]


In [80]:
# 17 replace all even elements with nan in R1
even_idex=R1%2==0
print(even_idex)
R1 = np.where(even_idex,np.nan,R1)
print(R1)

[[False False  True  True]
 [ True  True  True  True]
 [False  True False False]]
[[25. 35. nan nan]
 [nan nan nan nan]
 [17. nan 19. 23.]]


In [82]:
# 18 count number of nan in R1
print(np.isnan(R1).sum())

7


In [70]:
# 19   Check the Output of this code 

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
