# Assignment Numpy


In [4]:
#1.create a numpy array of 5 zeros. check datatype, itemsize and shape of above
import numpy as np
arr=np.zeros(5)
print(arr)
print(arr.dtype)
print(arr.itemsize)
print(arr.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [9]:
#2.create a numpy array of ones of shape (5,4)
arr=np.ones(shape=(5,4))
print(arr)
print(arr.dtype)
print(arr.itemsize)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
8
(5, 4)


In [15]:
#3.create a matrix of shape 4,5 with numbers from 1-20
arr=np.random.randint(1,20,size=(4,5))
print(arr)

[[13  3  3 18 10]
 [13  3 18  2  5]
 [ 5 16 15 12  9]
 [13  7  6  3 18]]


In [16]:
#4.multiply all elements of above array by 10
arr=arr*10
print(arr) #will multiplu element by element

[[130  30  30 180 100]
 [130  30 180  20  50]
 [ 50 160 150 120  90]
 [130  70  60  30 180]]


In [4]:
#5.print odd elements from array
import numpy as np
arr=np.arange(10,22).reshape(4,3)
print(arr)
print()
print(arr[arr%2!=0])

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]

[11 13 15 17 19 21]


In [5]:
#6.replace all even elements by their negative
import numpy as np
arr=np.arange(10,22).reshape(4,3)
print(arr)
print()
even_arr=arr%2==0
print(even_arr)
print()
print(np.where(even_arr, -arr, arr))


[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]

[[ True False  True]
 [False  True False]
 [ True False  True]
 [False  True False]]

[[-10  11 -12]
 [ 13 -14  15]
 [-16  17 -18]
 [ 19 -20  21]]


In [6]:
#7.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1=np.linspace(1,16,16).reshape(4,4)
print(m1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [7]:
#8create a transpose of above matrix call it M2
m1=np.linspace(1,16,16).reshape(4,4)
print(m1)
print()

m2=m1.T
print(m2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [8]:
#9.find sum of above matrix M3 = (M1 + M2)
m1=np.linspace(1,16,16).reshape(4,4)
print(m1)
print()

m2=m1.T
print(m2)
print()
m3=m1+m2
print(m3)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [20]:
#9.Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1=m3.T
print(mt1)
print()
if m3.all()==mt1.all():
    print('matrix are equal')
else:
    print('not equal')

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

matrix are equal


In [13]:
mt1=m3.T
print(mt1)
print()
for i in range(4):
    for j in range(4):
        if m3[i,j]==mt1[i,j]:
            break
        else:
            print('Not Equal')
print('Matrix are equal')

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

Matrix are equal


In [14]:
#10.find diffrence of M4 = (M1 - M2)
m4=m1-m2
print(m1)
print()
print(m2)
print()
print(m4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [30]:
#11.Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt2=m4.T
print(mt2)
print()
print(m4)
#if M4 == MT2
if np.allclose(m4,mt2):
    print('matrix are equal')
else:
    print('not equal')
#if M4 == -MT2
if np.allclose(m4,-mt2):
    print('matrix are equal')
else:
    print('not equal')

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
not equal
matrix are equal


In [2]:
#12.create a matrix (3x4) R1 of random numbers between 10-40
import numpy as np
r1=np.random.randint(10,40,(3,4))
print(r1)

[[11 28 23 25]
 [37 35 23 10]
 [18 23 27 11]]


In [3]:
#13.find min and max column wise
print(r1.min(axis=0))
print(r1.max(axis=0))


[11 23 23 10]
[37 35 27 25]


In [47]:
#14.replace the last column with sum of all the columns
r1[:,3]=r1[:,0]+r1[:,1]+r1[:,2]+r1[:,3]
print(r1)
print()
print(r1[:,3])

[[ 23  20  22 233]
 [ 27  34  39 339]
 [ 12  29  35 257]]

[233 339 257]


In [4]:
#15.create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,(3,4))
print(r1)

[[12 25 31 28]
 [23 19 13 27]
 [21 27 28 24]]


In [17]:
#16.replace all even elements with nan in R1
r1=np.random.randint(10,40,(3,4))
print(r1)
print()
r1=r1.astype(np.float32)
r1[r1%2==0]=np.nan
print(r1)

[[39 14 14 19]
 [33 34 32 24]
 [30 37 34 14]]

[[39. nan nan 19.]
 [33. nan nan nan]
 [nan 37. nan nan]]


In [18]:
#17.count number of nan in R1
print(np.isnan(r1).sum())

8


In [71]:
#18. predict output
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print()
print(a2)
a3 = np.append(a1,a2)
print()
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
