## NUMPY

- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


## Set 1

#### - create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above

In [1]:
import numpy as np
r = np.zeros(5)
print(r)
print("Datatype is: ",r.dtype)
print("Itemsize is: ",r.itemsize)
print("Shape is: ",r.shape)
r = np.array([0,0,0,0,0])
print(r)
print("Datatype is: ",r.dtype)
print("Itemsize is: ",r.itemsize)
print("Shape is: ",r.shape)

[0. 0. 0. 0. 0.]
Datatype is:  float64
Itemsize is:  8
Shape is:  (5,)
[0 0 0 0 0]
Datatype is:  int32
Itemsize is:  4
Shape is:  (5,)


#### - create a numpy array of ones of shape (5,4)

In [2]:
r = np.ones(20).reshape((5,4)) # reshape: returns a changed copy Original is unchanged, resize returns None Inplace change
print(r)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### - create a matrix of shape 4,5 with numbers from 1-20

In [3]:
r = np.arange(1,21).reshape(4,5)
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### - multiply all elements of above array by 10

In [4]:
m =  r*10
print(m)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


#### - print odd elements from array

In [5]:
#boolean indexing
#print(r%2!=0)
print("r is : \n",r)
idx = r % 2 != 0
print("\nOdd elements:")
print(r[idx])

r is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Odd elements:
[ 1  3  5  7  9 11 13 15 17 19]


#### - replace all even elements by their negative

In [6]:
print("r is : \n",r)
idx = r % 2 == 0
r[idx] = -r[idx]

print("\n Modified even elements:")
print(r)

r is : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 Modified even elements:
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


## Set 2 

#### - create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [7]:
m1 = np.linspace(1,16,16).reshape(4,4)
print(m1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


#### - create a transpose of above matrix call it M2

In [8]:
print("m1 is :\n",m1)
print("\nTranspose ")
m2 =m1.transpose()
print(m2)
print("\nTranspose using Attribute ")
m2 = m1.T
print(m2)

m1 is :
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Transpose 
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

Transpose using Attribute 
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


#### - find sum of above matrix M3 = (M1 + M2)

In [9]:
m3 = m1+m2
print(m3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


#### - Find Transpose of M3, Call it MT1. Check if M3 == MT1                                      ============================>

In [10]:
mt1 = m3.T
#if (m3==m3.T): # Ambiguous as multiple t/f values
if ((m3==m3.T).all()): #. precendence over ==
    print("Equal ")
else:
    print("Not Equal")

Equal 


#### - find difference of M4 = (M1 - M2)

In [11]:
m4 = m1 - m2
print(m4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


#### - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [12]:
mt2 = m4.T
if ((m4==mt2).all()): 
    print("Equal ")
else:
    print("Not Equal")
    
mt2 = m4.T
if ((m4==-mt2).all()): 
    print("Equal ")
else:
    print("Not Equal")

Not Equal
Equal 


## Set 3

#### - create a matrix (3x4) R1 of random numbers between 10-40

In [23]:
r1 = np.random.randint(10,40,12).reshape((3,4)) 
print(r1)
#np.array([1,2,2])


[[35 16 27 33]
 [15 15 15 29]
 [19 21 31 27]]


#### - find min and max column wise

In [24]:
print(np.amax(r1,axis = 0)) #column wise
print(np.amin(r1,axis = 0)) #column wise

[35 21 31 33]
[15 15 15 27]


#### - replace the last column with sum of all the columns

In [25]:
# print(r1[,3]) #invalid syntax
print("~~r1 is: \n",r1)
print("\nLast column is: \n",r1[:,3:])
s = np.sum(r1,axis = 0)
print("\nSum of columns is --last element of s Array will not be in r1 as size varies-- : \n",s)
s.resize((3,1)) 
r1[:,3:] = s

print("\nModified r1 is \n", r1)

~~r1 is: 
 [[35 16 27 33]
 [15 15 15 29]
 [19 21 31 27]]

Last column is: 
 [[33]
 [29]
 [27]]

Sum of columns is --last element of s Array will not be in r1 as size varies-- : 
 [69 52 73 89]

Modified r1 is 
 [[35 16 27 69]
 [15 15 15 52]
 [19 21 31 73]]


## Set 4

#### - create a matrix (3x4) R1 of random numbers between 10-40


In [29]:
r1 = (np.round(np.random.rand(12)*100)).reshape((3,4)) 
print(r1) 

[[92. 21. 23. 92.]
 [ 3. 79. 85. 75.]
 [61. 88. 11. 21.]]


#### - replace all even elements with nan in R1


In [30]:
idx = r1%2 ==0
r1[idx] = np.nan
print(r1)

[[nan 21. 23. nan]
 [ 3. 79. 85. 75.]
 [61. nan 11. 21.]]


#### - count number of nan in R1

In [31]:
c=0
for row in r1:
    for val in row:
        if np.isnan(val):
            c+=1
print('Number of nans= ',c)

Number of nans=  3


In [19]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
