In [10]:
# 1. create a numpy array of 5 zeros.
import numpy as np
arr = np.array([0,0,0,0,0])
print(arr)
print()

# check datatype, itemsize and shape of above
print(f'{arr} array datatype is {arr.dtype}, array size is {arr.size}, array shape is {arr.shape}')

# len(arr) 5
# array size is the total no. of elements

[0 0 0 0 0]

[0 0 0 0 0] array datatype is int32, array size is 5, array shape is (5,)


In [12]:
# 2. create a numpy array of ones of shape (5,4)
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# 3. create a matrix of shape 4,5 with numbers from 1-20
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
# 4. multiply all elements of above array by 10
arr * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [17]:
# arr isn't changed

In [21]:
# 5. print odd elements from array
arr[arr%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
# 6. replace all even elements by their negative
np.where(arr%2!=1,-arr,arr)

array([[  1,  -2,   3,  -4,   5],
       [ -6,   7,  -8,   9, -10],
       [ 11, -12,  13, -14,  15],
       [-16,  17, -18,  19, -20]])

In [37]:
# 7. create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.arange(1,17).reshape(4,-1)
M1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# 8. create a transpose of above matrix call it M2
M2 = M1.T
M2

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [39]:
# 9. find sum of above matrix M3 = (M1 + M2)
M3 = (M1 + M2)
M3

array([[ 2,  7, 12, 17],
       [ 7, 12, 17, 22],
       [12, 17, 22, 27],
       [17, 22, 27, 32]])

In [56]:
# 10. Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print(MT1)
print()

print(f'M3 == MT1 : {np.array_equal(M3,MT1)}')

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

M3 == MT1 : True


In [43]:
# 11. find diffrence of M4 = (M1 - M2)
M4 = (M1 - M2)
M4

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [59]:
# 12. Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print(MT2)
print()

print(f'M4 == MT2 : {np.array_equal(M4,MT2)}') 
print()

print(f'M4 == -MT2 : {np.array_equal(M4,-MT2)}') 

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

M4 == MT2 : False

M4 == -MT2 : True


In [83]:
# 13. create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,41,(3,4))
R1

array([[20, 28, 11, 37],
       [32, 10, 14, 37],
       [25, 10, 39, 33]])

In [84]:
# 14. find min and max column wise
print('column wise min : ', R1.min(axis=0))
print('column wise max : ', R1.max(axis=0))

column wise min :  [20 10 11 33]
column wise max :  [32 28 39 37]


In [85]:
# 15. replace the last column with sum of all the columns
R1[len(R1)-1] = R1.sum(axis=0)
R1

array([[ 20,  28,  11,  37],
       [ 32,  10,  14,  37],
       [ 77,  48,  64, 107]])

In [95]:
# 16. create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,41,(3,4))
print(R1)
print()

# replace all even elements with nan in R1
R1 = np.where(R1%2==0, np.NaN, R1)
print(R1)
print()

# count number of nan in R1
print(np.isnan(R1))
np.isnan(R1).sum()

[[26 27 36 30]
 [11 31 14 25]
 [25 17 24 31]]

[[nan 27. nan nan]
 [11. 31. nan 25.]
 [25. 17. nan 31.]]

[[ True False  True  True]
 [False False  True False]
 [False False  True False]]


5

In [97]:
# 17. check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
