In [6]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above
import numpy

arr =  numpy.zeros(5, dtype = int)  
print("Matrix a : \n", arr)  

print(arr.dtype)
print(arr.shape)
print(arr.itemsize)

Matrix a : 
 [0 0 0 0 0]
int32
(5,)
4


In [8]:
#create a numpy array of ones of shape (5,4)
import numpy

arr =  numpy.ones([5,4], dtype = int)  
print("Matrix a : \n", arr)

Matrix a : 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
#create a matrix of shape 4,5 with numbers from 1-20
#multiply all elements of above array by 10
#print odd elements from array
import numpy

a = numpy.arange(20).reshape(4,5)
print("Matrix a : \n", a)

print("Matrix a : \n", a)
print (a * 10)

answer = a[a%2==1]
print (answer)
#replace all even elements by their negative
answer = a[a%2==0]*-1
print (answer)

Matrix a : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Matrix a : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]
[ 1  3  5  7  9 11 13 15 17 19]
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18]


In [ ]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
#create a transpose of above matrix call it M2
#find sum of above matrix M3 = (M1 + M2)

In [38]:
import numpy as np

m1 = np.arange(16).reshape(4,4)
print(m1)
m2=np.transpose(m1)
print(m2)
print(" matrix M3 = (M1 + M2)")
m3=np.add(m1, m2)
print("M3\n")
print(m3)

#Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1=np.transpose(m3)
print(mt1)

comparison = mt1 == m3
equal_arrays = comparison.all()

print(equal_arrays)

#find diffrence of M4 = (M1 - M2)
m4=np.subtract(m1,m2)
print("M4\n")
print(m4)
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt2=np.transpose(m4)
print(mt2)
print("M4 == MT2\n")
c1 = m4 == mt2
eq = c1.all()

print(eq)
print("M4 == -MT2\n")
c2 = m4 == -mt2
eq1= c2.all()
print(eq1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
 matrix M3 = (M1 + M2)
M3

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
True
M4

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
M4 == MT2

False
M4 == -MT2

True


In [50]:
#create a matrix (3x4) R1 of random numbers between 10-40
#find min and max column wise
#replace the last column with sum of all the columns

import numpy as np
random_matrix_array = np.random.randint(10,40,size=(3,4))
print(random_matrix_array)

print("Min ", np.amin(random_matrix_array))
print("Max ", np.amax(random_matrix_array))
b=np.sum(random_matrix_array)
print("\nSum of arr : ",np.sum(random_matrix_array) ) 

for i in range(3):
    random_matrix_array[i,3]=b

print('replace the last column with sum of all the columns: ')
print(random_matrix_array)

[[13 30 37 31]
 [34 30 20 34]
 [26 30 34 23]]
Min  13
Max  37

Sum of arr :  342
replace the last column with sum of all the columns: 
[[ 13  30  37 342]
 [ 34  30  20 342]
 [ 26  30  34 342]]


In [64]:
#create a matrix (3x4) R1 of random numbers between 10-40
#replace all even elements with nan in R1
#count number of nan in R1

import numpy as np
a = np.random.randint(10,40,size=(3,4))
print(a)

e_idx=a%2==0

print(e_idx)
print(np.where(e_idx,np.nan,a**1))
a=np.where(e_idx,np.nan,a**1)
print(a)

[[26 16 16 23]
 [34 26 15 30]
 [28 16 35 21]]
[[ True  True  True False]
 [ True  True False  True]
 [ True  True False False]]
[[nan nan nan 23.]
 [nan nan 15. nan]
 [nan nan 35. 21.]]
[[nan nan nan 23.]
 [nan nan 15. nan]
 [nan nan 35. 21.]]


In [67]:
#check output of this code
a1 = np.arange(1,10).reshape(3,3)

a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print("a3 1st")
print(a3)
print("a3 2nd")
a3 = np.append(a1,a2, axis = 0)
print(a3)
print("a3 3rd")
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
a3 1st
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
a3 2nd
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
a3 3rd
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
