## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


### 1. create a numpy array of 5 zeros.
###### check datatype, itemsize and shape of above

In [3]:
import numpy as np

In [5]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [10]:
print(zero_array.dtype)
print(type(zero_array))

float64
<class 'numpy.ndarray'>


In [11]:
print(zero_array.size)
print(len(zero_array))

5
5


In [12]:
print(zero_array.shape)

(5,)


### 2. create a numpy array of ones of shape (5,4)

In [15]:
one_array = np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### create a matrix of shape 4,5 with numbers from 1-20
###### multiply all elements of above array by 10
###### print odd elements from array
###### replace all even elements by their negative

In [41]:
arr1 = np.arange(1,21).reshape(4,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [42]:
arr1 * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [47]:
arr1[arr1%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
arr1[arr1%2 == 0] * (-1)

array([ -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20])

### create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
###### create a transpose of above matrix call it M2
###### find sum of above matrix M3 = (M1 + M2)
###### Find Transpose of M3, Call it MT1. Check if M3 == MT1
###### find diffrence of M4 = (M1 - M2)
###### Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [51]:
M1 = np.linspace(1, 16, 16).reshape(4,4)
M1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [52]:
M2 = np.transpose(M1)
M2

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]])

In [53]:
M3 = (M1 + M2)
M3

array([[ 2.,  7., 12., 17.],
       [ 7., 12., 17., 22.],
       [12., 17., 22., 27.],
       [17., 22., 27., 32.]])

In [54]:
MT1 = np.transpose(M3)
MT1

array([[ 2.,  7., 12., 17.],
       [ 7., 12., 17., 22.],
       [12., 17., 22., 27.],
       [17., 22., 27., 32.]])

In [55]:
MT1 == M3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
M4 = (M1 - M2)
M4

array([[ 0., -3., -6., -9.],
       [ 3.,  0., -3., -6.],
       [ 6.,  3.,  0., -3.],
       [ 9.,  6.,  3.,  0.]])

In [57]:
MT2 = np.transpose(M4)
MT2

array([[ 0.,  3.,  6.,  9.],
       [-3.,  0.,  3.,  6.],
       [-6., -3.,  0.,  3.],
       [-9., -6., -3.,  0.]])

In [58]:
M4 == MT2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [59]:
M4 == -MT2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### create a matrix (3x4) R1 of random numbers between 10-40
###### find min and max column wise
###### replace the last column with sum of all the columns

In [63]:
R1 = np.random.randint(10,40,12).reshape(3,4)
R1

array([[34, 20, 10, 24],
       [14, 19, 37, 31],
       [26, 18, 11, 39]])

In [67]:
R1.min(axis=0)

array([14, 18, 10, 24])

In [68]:
R1.max(axis=0)

array([34, 20, 37, 39])

In [72]:
R1[-1, :] = R1.sum(axis=0)
R1

array([[34, 20, 10, 24],
       [14, 19, 37, 31],
       [74, 57, 58, 94]])

### create a matrix (3x4) R1 of random numbers between 10-40
###### replace all even elements with nan in R1
###### count number of nan in R1

In [83]:
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)
R1 = R1.astype('float64')
R1

[[29 26 21 37]
 [19 37 33 35]
 [38 35 20 17]]


array([[29., 26., 21., 37.],
       [19., 37., 33., 35.],
       [38., 35., 20., 17.]])

In [85]:
R1[R1%2 == 0] = np.nan
R1

C:\Users\pallavi.saxena\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in remainder
  """Entry point for launching an IPython kernel.


array([[29., nan, 21., 37.],
       [19., 37., 33., 35.],
       [nan, 35., nan, 17.]])

In [88]:
np.count_nonzero(R1)

12

In [89]:
np.isnan(R1)

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [90]:
np.count_nonzero(np.isnan(R1))

3

### check output of this code
`
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`

In [91]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [60]:
print(dir(np.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bit_generator', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard