## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

### Q1 create a numpy array of 5 zeros. check datatype, itemsize and shape of above

In [9]:
arr_zeros = np.zeros (5)
print (arr_zeros)
print (arr_zeros.dtype)
print (arr_zeros.itemsize) # means each element is 8 bytes
print (arr_zeros.shape) #5 rows 1 column

[0. 0. 0. 0. 0.]
float64
8
(5,)


### Q2 create a numpy array of ones of shape (5,4)

In [12]:
arrOnes = np.ones ((5,4))
arrOnes

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Q3 create a matrix of shape 4,5 with numbers from 1-20

In [56]:
mat = np.random.randint (1, 21, 20).reshape (4,5)
mat

array([[ 7,  4,  8, 14, 12],
       [20,  1, 10,  9,  8],
       [19,  1, 16,  4,  2],
       [10, 19, 14,  4,  6]])

### Q4 - multiply all elements of above array by 10

In [57]:
print (mat*10)

[[ 70  40  80 140 120]
 [200  10 100  90  80]
 [190  10 160  40  20]
 [100 190 140  40  60]]


### Q5 - print odd elements from array

In [58]:
pos = mat % 2 !=0 # retuns a matrix of True and false 
print (mat[pos]) #when use above T and F matrix gives output for only True value 

[ 7  1  9 19  1 19]


In [59]:
#self practice

pos = mat % 2 ==0
pos
print ( np.where (pos, mat**2, mat //2) ) ##np.where does operation mat**2 at palces even and other for odd positions

[[  3  16  64 196 144]
 [400   0 100   4  64]
 [  9   0 256  16   4]
 [100   9 196  16  36]]


### Q6 - replace all even elements by their negative

In [60]:
negmat = mat*-1
negmat

array([[ -7,  -4,  -8, -14, -12],
       [-20,  -1, -10,  -9,  -8],
       [-19,  -1, -16,  -4,  -2],
       [-10, -19, -14,  -4,  -6]])

### Q7 - create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [67]:
M1 = np.linspace (1,16,16).reshape (4,4)
M1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

### Q8 - create a transpose of above matrix call it M2

In [68]:
M2 = M1.T
M2

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]])

### Q9 - find sum of above matrix M3 = (M1 + M2)

In [69]:
M3 = M1 + M2
M3

array([[ 2.,  7., 12., 17.],
       [ 7., 12., 17., 22.],
       [12., 17., 22., 27.],
       [17., 22., 27., 32.]])

### Q10 - Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [73]:
MT1 = M3.T
MT1
print (M3 == MT1) #Yes they are equal

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Q11 - Find diffrence of M4 = (M1 - M2)

In [74]:
M4 = M1- M2
M4

array([[ 0., -3., -6., -9.],
       [ 3.,  0., -3., -6.],
       [ 6.,  3.,  0., -3.],
       [ 9.,  6.,  3.,  0.]])

### Q12 - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [80]:
MT2 = M4.T
print (MT2 == M4) # Not equal
print (M4 == - MT2) # Equal

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Q13 - create a matrix (3x4) R1 of random numbers between 10-40

In [86]:
mat = np.random.randint (10,40,12).reshape (3,4)
mat

array([[18, 16, 27, 30],
       [39, 37, 10, 38],
       [12, 27, 38, 20]])

### Q14 - find min and max column wise

In [94]:
print (np.max (mat,  axis = 0)) # column wise max 
print (np.max (mat,  axis = 1)) # row wise max

[39 37 38 38]
[30 39 38]


### Q15 - replace the last column with sum of all the columns

In [96]:
mat [2] = np.sum (mat, axis = 0)
mat

array([[18, 16, 27, 30],
       [39, 37, 10, 38],
       [69, 80, 75, 88]])

### Q16 - create a matrix (3x4) R1 of random numbers between 10-40

In [113]:
R1 = np.arange (10,22, dtype = np.float64).reshape (3,4)
R1

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]])

### Q17 - replace all even elements with nan in R1

In [115]:
pos = mat %2 == 0
R1 [pos] = np.nan  #np.nan works with flaot 64 only, tried other random.randint, or without dtype nan assignemnt gives error
R1

array([[10., 11., 12., 13.],
       [nan, 15., 16., nan],
       [nan, nan, 20., 21.]])

### Q18 - count number of nan in R1

In [121]:
print (np.isnan(R1)) #just for visibility of NaN's , this line is not required
print ((np.isnan(R1).sum())) #sum will give count of only trues in expression isnan

[[False False False False]
 [ True False False  True]
 [ True  True False False]]
4


### Q19 check output of this code
 - a1 = np.arange(1,10).reshape(3,3)
 - a2 = np.arange(11,20).reshape(3,3)
 - a3 = np.append(a1,a2)
 - print(a3)
 - a3 = np.append(a1,a2, axis = 0)
 - print(a3)
 - a3 = np.append(a1,a2, axis = 1)
 - print(a3)

In [125]:
# 1 2 3
# 4 5 6 = a1
# 7 8 9

# 11 12 13
# 14 15 16 = a2
# 17 18 19

# 1 2 3 4 5 6 7 8 9 11 12 13 14 5 16 17 18 19 - a3

# 1 2 3
# 4 5 6  - a3
# 7 8 9
# 11 12 13
# 14 15 16 
# 17 18 19

# 1 2 3 11 12 13
# 4 5 6 14 15 16 - a3
# 7 8 9 17 18 19


In [139]:
a1 = np.arange(1,17).reshape(4,4)
a2 = np.arange(11,27).reshape(4,4)
# a3 = np.append(a1,a2, axis = 0)
# print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
print (np.split(a3, 4, axis = 1)) #does a split along columns (different from axis = 0 for col)
print ()
print (np.split(a3, 4, axis = 0)) # does a split along rows (different from axis = 1 for row)
print ()
print (np.split(a3, [2,4], axis = 1))
print ()
print (np.split(a3, [2,3], axis = 0)) # does following split [:2],[2:3] and [3:] ie slicing done along row

[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]
 [ 9 10 11 12 19 20 21 22]
 [13 14 15 16 23 24 25 26]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]]), array([[11, 12],
       [15, 16],
       [19, 20],
       [23, 24]]), array([[13, 14],
       [17, 18],
       [21, 22],
       [25, 26]])]

[array([[ 1,  2,  3,  4, 11, 12, 13, 14]]), array([[ 5,  6,  7,  8, 15, 16, 17, 18]]), array([[ 9, 10, 11, 12, 19, 20, 21, 22]]), array([[13, 14, 15, 16, 23, 24, 25, 26]])]

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]]), array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])]

[array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]]), array([[ 9, 10, 11, 12, 19, 20, 21, 22]]), array([[13, 14, 15, 16, 23, 24, 25, 26]])]
